server:
  port: 80
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shopping?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 54@Xdj.con
    #password: root
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: jia2020redis
    # springboot2.x以上如此配置，由于2.x的客户端是lettuce 单位要带上
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: 2000ms
      shutdown-timeout: 100ms
  mail:
    username: 750186098@qq.com
    port: 464
    password: 123456
    properties:
      mail:
        auth: true
        smtp:
          starttls:
            enable: true
            required: true
        ssl:
          enable: true
  cache:
    ehcache:
      #是否启用ehcache缓存
      enable: true
      #jvm内存中缓存的key数量
      heap: 1000
      #堆外内存大小, 单位: MB
      offheap: 100
      #磁盘持久化目录, 为空表示不进行持久化
      diskDir: /ehcache
      #持久化到磁盘的大小, 单位: MB
      disk: 500
      #缓存过期时间, 单位: 秒, 0表示不过期
      ttl: 1800
      config: classpath:ehcache.xml
  resources:
    static-locations: classpath:/static
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates
logging:
  level:
    org.springframework: info
    com.xdj.interfaces.mallinterface.mapper: debug
mybatis:
  mapper-locations: classpath:mybatis/*.*
  type-aliases-package: com.xdj.com.model.entity
  config-location: classpath:mybatis-config.xml
  mybatis.typeAliasesPackage: com.xdj.www.entity
  mybatis.mapperLocations: classpath:mybatis/*.*


