server:
  port: 80
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  messages:
    basename: static/i18n/messages
    encoding: UTF-8
  mail:
    username: amberxqq@163.com
    port: 465
    host: smtp.163.com
    password: qq1013
    properties:
      mail:
        auth: true
        smtp:
          starttls:
            enable: true
            required: true
        ssl:
          enable: true
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: jia2020redis
    # springboot2.x以上如此配置，由于2.x的客户端是lettuce 单位要带上
    lettuce:
      shutdown-timeout: 100ms
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: 2000ms


  resources:
    static-locations: classpath:/static
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates
# 日志配置
logging:
  level:
    org.springframework: info
    com.xdj.interfaces.mallinterface.mapper: debug
# mybatis 相关配置
mybatis:
  mapper-locations: classpath:mybatis/*.*
  type-aliases-package: com.xdj.com.model.entity
  config-location: classpath:mybatis-config.xml
  mybatis.typeAliasesPackage: com.xdj.www.entity
  mybatis.mapperLocations: classpath:mybatis/*.*

